### PR TITLE
Pure AS3 example added.

### PR DESCRIPTION
**Pull request by MindScriptAct**
Flash(Animate) IDE is not used for as3 coding for ages... added pure code example.

### CODE REVIEW

**Comment by EddieOne** [comment]
Thanks for sharing. It looks good. I will test this tomorrow.

**Comment by EddieOne** [comment]
I will merge it. If you want something with less code, we can export buttons via swc file.

**Comment by MindScriptAct** [comment]
I think its not needed. simple button and label can stay in code.
I also have couple of ideas how to improve it more! Make it stand alone window. That could be opened with key press. Add some imput.. for example text field to put your appId. (instead of hard coding it..)

**Comment by EddieOne** [comment]
Most developers are copy pasting the code, adding fancy debug stuff might interfere. We could always create a separate folder with a testing swf

**Comment by MindScriptAct** [comment]
I sure we can adapt and please many different kinds of developers.. ;)

**Pull request merged**
